---
downloads: /root/.ansible-downloads/

username: "root"

bash_aliases: []

configure_bootstrap: yes
configure_virtualenv: yes

python_versions: [2.7, 3.7]
python_virtualenvs: 
- path: /root/venv/py2
  python: python2.7
- path: /root/venv/py3
  python: python3.7

chisel_version: '1.3.1'