---
downloads: /root/.ansible-downloads/

username: "root"

bash_aliases: []

configure_bootstrap: yes
configure_dotfiles: yes
configure_virtualenv: yes
configure_keys: yes

dotfiles_repo: https://github.com/BrashEndeavours/dotfiles
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: /root/Documents/dotfiles
dotfiles_files:
  - .bashrc
  - .gitconfig
  - .vimrc
  - .config/cherrytree/config.cfg
  - .tmux.conf

python_versions: [2.7, 3.7]
python_virtualenvs: 
- path: /root/venv/py2
  python: python2.7
- path: /root/venv/py3
  python: python3.7
