---
- name: Converge
  hosts: localhost
  become: yes
  gather_facts: yes

  vars_files:
    - default.config.yml
    # Remove if not using secrets to store private keys.
    - secrets/ssh_keys.yml      

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  tasks:
  - include_tasks: tasks/user.yml
        
  - include_tasks: tasks/dotfiles.yml
    when: configure_dotfiles

  - include_tasks: tasks/python_virtualenv.yml
    when: configure_virtualenv

  - include_tasks: tasks/ssh_keys.yml
    when: configure_keys

  - include_tasks: tasks/install_git.yml

  - include_tasks: tasks/install_AutoRecon.yml
  - include_tasks: tasks/install_chisel.yml
  - include_tasks: tasks/install_gobuster.yml
  - include_tasks: tasks/install_LinEnum.yml
  - include_tasks: tasks/install_nishang.yml
  - include_tasks: tasks/install_one-lin3r.yml
  - include_tasks: tasks/install_OSCP_report_templates.yml
  - include_tasks: tasks/install_pspy.yml
  - include_tasks: tasks/install_PowerSploit.yml
  - include_tasks: tasks/install_proxychains-ng.yml
  - include_tasks: tasks/install_SecLists.yml
  - include_tasks: tasks/install_sherlock.yml
  - include_tasks: tasks/install_sshuttle.yml
  - include_tasks: tasks/install_webshell.yml
  - include_tasks: tasks/install_wkhtmltopdf.yml

  - include_tasks: tasks/update_polenum.yml

  - include_tasks: tasks/install_custom_samba_prereqs.yml
  - include_tasks: tasks/install_custom_samba.yml

  - include_tasks: tasks/add_aliases.yml
