---
- name: Converge
  hosts: localhost
  become: yes
  gather_facts: no

  vars_files:
    - default.config.yml
    - secrets/ssh_keys.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  tasks:
  - include_tasks: tasks/user.yml
        
  - include_tasks: tasks/dotfiles.yml
    when: configure_dotfiles

  - include_tasks: tasks/python_virtualenv.yml
    when: configure_virtualenv

  - include_tasks: tasks/ssh_keys.yml
    when: configure_keys
