---
# https://github.com/M4ximuss/Powerless
- name: Clone powerless from repository
  git:
    repo: "https://github.com/M4ximuss/Powerless.git"
    dest: /opt/powerless
    update: yes

- name: Download archived accesschk-2003-xp.exe
  get_url:
    url: https://github.com/ankh2054/windows-pentest/blob/master/Privelege/accesschk-2003-xp.exe
    validate_certs: no
    dest: /opt/powerless/
    mode: 555
    owner: root

- name: Download archived accesschk-2008-vista.exe
  get_url:
    url: https://github.com/ankh2054/windows-pentest/blob/master/Privelege/accesschk-2008-vista.exe
    validate_certs: no
    dest: /opt/powerless/
    mode: 555
    owner: root
