---
# https://github.com/rofl0r/proxychains-ng
- name: Copy the proxychains-ng from repository
  git:
    repo: "https://github.com/rofl0r/proxychains-ng.git"
    dest: /opt/proxychains-ng
    update: yes

- name: Configure proxychains-ng
  command: "./configure"
  args:
    chdir: /opt/proxychains-ng/

- name: Compile proxychains-ng
  command: "make"
  args:
    chdir: /opt/proxychains-ng/

- name: Install proxychains-ng
  command: "make install"
  args:
    chdir: /opt/proxychains-ng/