---
# https://github.com/PowerShellMafia/PowerSploit
- name: Copy PowerSploit from repository
  git:
    repo: "https://github.com/PowerShellMafia/PowerSploit.git"
    dest: /opt/PowerSploit
    update: yes
