---
# https://github.com/tennc/webshell
- name: Ensure git is installed.
  apt:
    name: "git"
    state: present

- name: Copy the webshell project from repository
  git:
    repo: "https://github.com/tennc/webshell.git"
    dest: /opt/webshell
    update: yes
