---
# https://github.com/Hackplayers/evil-winrm
- name: Install rubygems and ruby-dev
  apt:
    name: "{{item}}"
  loop:
  - rubygems
  - ruby-dev

- name: Install gem packages
  gem:
    name: "{{item}}"
  loop:
  - winrm
  - winrm-fs
  - colorize
  - stringio

- name: Ensure git is installed.
  apt:
    name: "git"
    state: present

- name: Copy Evil-Winrm from repository
  git:
    repo: "https://github.com/Hackplayers/evil-winrm"
    dest: /opt/evil-winrm
    update: yes 
    force: yes

- name: Set evil-winrm aliases
  set_fact:
    evil_winrm_aliases: 
    - { alias: 'evil-winrm', command: 'ruby /opt/evil-winrm/evil-winrm.rb' }

- name: Merge evil-winrm aliases
  set_fact:
    bash_aliases: "{{ bash_aliases + evil_winrm_aliases }}"