---
# https://github.com/whoisflynn/OSCP-Exam-Report-Template
- name: Ensure git is installed.
  apt:
    name: "git"
    state: present

- name: Copy OSCP report templates from repository
  git:
    repo: "https://github.com/whoisflynn/OSCP-Exam-Report-Template.git"
    dest: "{{ homefolder + 'Documents/OSCP-Templates' }}"
    update: yes
