---
# https://github.com/swisskyrepo/PayloadsAllTheThings
- name: Copy the PayloadsAllTheThings from repository
  git:
    repo: "https://github.com/swisskyrepo/PayloadsAllTheThings.git"
    dest: /opt/PayloadsAllTheThings
    update: yes
