---
# https://github.com/samratashok/nishang
- name: Ensure git is installed.
  apt:
    name: "git"
    state: present

- name: Copy nishang from repository
  git:
    repo: "https://github.com/samratashok/nishang.git"
    dest: /opt/nishang
    update: yes
