---
# https://github.com/swisskyrepo/PayloadsAllTheThings
- name: Ensure git is installed.
  apt:
    name: "git"
    state: present

- name: Copy the PayloadsAllTheThings from repository
  git:
    repo: "https://github.com/swisskyrepo/PayloadsAllTheThings.git"
    dest: /opt/PayloadsAllTheThings
    update: yes
