---
- name: Ensure downloads directory exists (Required by travis)
  file:
    path: /root/Downloads
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Ensure git is installed.
  apt:
    name: "git"
    state: present

- name: Download nmap
  git:
    repo: "https://github.com/nmap/nmap.git"
    dest: /root/Downloads/nmap_src
    update: yes
  register: nmap_download

- name: Configure NMap
  command: ./configure
  args:
    chdir: /root/Downloads/nmap_src/
  when: nmap_download.changed

- name: Make NMap
  command: make -j4
  args:
    chdir: /root/Downloads/nmap_src/
  when: nmap_download.changed

- name: Install NMap
  command: make -j4 install
  args:
    chdir: /root/Downloads/nmap_src/
  when: nmap_download.changed
