---
# https://github.com/rebootuser/LinEnum
- name: Ensure git is installed.
  apt:
    name: "git"
    state: present

- name: Copy the LinEnum from repository
  git:
    repo: "https://github.com/rebootuser/LinEnum.git"
    dest: /opt/LinEnum
    update: yes
