---
# https://github.com/rofl0r/proxychains-ng
- name: Ensure git is installed.
  apt:
    name: "git"
    state: present

- name: Copy the proxychains-ng from repository
  git:
    repo: "https://github.com/rofl0r/proxychains-ng.git"
    dest: /opt/proxychains-ng
    update: yes
  register: proxychains

- name: Configure proxychains-ng
  command: "./configure"
  args:
    chdir: /opt/proxychains-ng/
  when: proxychains.changed

- name: Compile proxychains-ng
  command: "make"
  args:
    chdir: /opt/proxychains-ng/
  when: proxychains.changed

- name: Install proxychains-ng
  command: "make install"
  args:
    chdir: /opt/proxychains-ng/
  when: proxychains.changed