---
# https://github.com/Tib3rius/AutoRecon
- name: Ensure git is installed.
  apt:
    name: "git"
    state: present
    
- name: Copy AutoRecon from repository
  git:
    #Temporary, until PR for gobuster v3 is brought into main repo.
    repo: "https://github.com/BrashEndeavours/AutoRecon"
    dest: /opt/autorecon
    update: yes 
    force: yes

- name: Install AutoRecon
  pip: 
    executable: pip3
    requirements: /opt/autorecon/requirements.txt

- name: Set autorecon aliases
  set_fact:
    autorecon_aliases: 
    - { alias: 'autorecon', command: 'python3 /opt/autorecon/autorecon.py' }

- name: Merge autorecon aliases
  set_fact:
    bash_aliases: "{{ bash_aliases + autorecon_aliases }}"
